title = "Fractribution analysis"
baseURL = "https://docs.snowplow.io/accelerators/snowplow_fractribution/"

[params]
  description = "Tutorial for running fractional attribution on Snowplow data"
  author = "Poplin, Mike Robins, Zoe Loffler"
